import { Activity, Beef, CloudRain, DollarSign, Factory, Globe2, Ship, Wheat } from 'lucide-react';
import { exportacoes, fontes, historicoArroba, indicadoresBase, custos } from '../lib/data';
import { SparkChart } from '../components/SparkChart';

function Card({title,value,sub,icon:Icon}:{title:string;value:string;sub:string;icon:any}){return <div className="card"><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><h3>{title}</h3><div className="value">{value}</div><div className="sub">{sub}</div></div><Icon size={24} color="#37d67a"/></div></div>}

export default function Page(){
  const icons=[Beef,Wheat,Wheat,Factory,Ship,Globe2,DollarSign,CloudRain];
  const pesos=[15,14,12,-8,-6,10,18,8]; const score=73;
  return <main className="wrap"><section className="top"><div className="brand"><h1>DASHBOI — Mercado Pecuário</h1><p>Painel diário para decisão de compra, venda e confinamento. Instale no celular como PWA.</p></div><div className="badge">Atualização automática preparada: API Banco Central + base manual editável</div></section>
  <section className="grid hero"><div className="card"><span className="pill">Leitura executiva</span><div className="score">{score}/100</div><div className="bar"><span style={{width:`${score}%`}}/></div><p className="sub" style={{fontSize:15}}>Mercado <b style={{color:'#37d67a'}}>altista moderado</b>. Exportações fortes, dólar e escalas sustentam a arroba; custo de alimentação limita a margem do confinamento.</p></div><div className="card"><h3>Fatores do índice</h3>{['Exportações','China','Escalas','Dólar','Clima','Milho','Farelo soja','Consumo interno'].map((n,i)=><div key={n} style={{display:'flex',alignItems:'center',gap:10,margin:'9px 0'}}><span style={{width:95,fontSize:13,color:'#9bb8a8'}}>{n}</span><div className="bar" style={{flex:1,height:9}}><span style={{width:`${Math.abs(pesos[i])*4}%`,background:pesos[i]>=0?'linear-gradient(90deg,#37d67a,#8df5b8)':'linear-gradient(90deg,#ef6461,#f4c542)'}}/></div><b className={pesos[i]<0?'warn':''}>{pesos[i]>0?'+':''}{pesos[i]}</b></div>)}</div></section>
  <section className="grid cards">{indicadoresBase.map((c,i)=><Card key={c.title} {...c} icon={icons[i]}/>)}</section>
  <h2 className="section">Gráficos históricos</h2><section className="grid charts"><SparkChart title="Evolução da arroba MS" unit="R$ " data={historicoArroba}/><SparkChart title="Exportações mensais de carne bovina" unit="" data={exportacoes} variant="line2"/><SparkChart title="Custo estimado da alimentação" unit="R$ " data={custos}/><div className="card"><h3>Resumo operacional</h3><table className="table"><tbody><tr><th>Indicador</th><th>Status</th></tr><tr><td>Relação boi/milho</td><td>Favorável</td></tr><tr><td>Margem confinamento</td><td>Atenção por custo de dieta</td></tr><tr><td>Momento de venda</td><td>Monitorar escalas e B3</td></tr><tr><td>Risco principal</td><td>Queda China ou alta milho</td></tr></tbody></table></div></section>
  <h2 className="section">Fontes confiáveis para integração</h2><section className="grid sources">{fontes.map(([a,b])=><div className="card" key={a}><h3>{a}</h3><div className="sub">{b}</div></div>)}</section><p className="footer">Versão funcional testada para deploy na Vercel. Dados de arroba, escalas e custos podem ser atualizados em lib/data.ts. A rota /api/market já consulta a PTAX do Banco Central e serve de modelo para conectar Comex Stat, INMET e demais APIs.</p></main>
}
